workflows:
  android-debug-build:
    name: Android Debug Build
    environment:
      flutter: stable
      java: "11" # Corretto: java deve essere una stringa
      android:
        sdk: "34" # Versione SDK

    scripts:
      - name: Build Android APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - "Callrecorder38@gmail.com" # Inserisci la tua email qui tra le virgolette
