workflows:
  cordova_build:
    name: Build Cordova Android APK
    environment:
      java: "11"                   # Imposta Java 11
      node: "18"                   # Imposta Node 18
    scripts:
      - name: Installazione Cordova
        script: |
          npm install -g cordova

      - name: Installazione Android Build Tools
        script: |
          yes | sdkmanager "build-tools;34.0.0" "platforms;android-34"

      - name: Aggiunta piattaforma Android
        script: |
          cordova platform add android

      - name: Compilazione APK
        script: |
          cordova build android --release

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - "tuaemail@example.com"
        notify:
          success: true
          failure: true
