workflows:
  cordova_build:
    name: Cordova Build Workflow
    max_build_duration: 60
    environment:
      node: 16.18.0
      vars:
        CORDOVA_ANDROID_VERSION: 11.0.0
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install -g cordova
          cordova telemetry off
      - name: Build the project
        script: |
          cordova platform add android@${CORDOVA_ANDROID_VERSION}
          cordova build android --release
    artifacts:
      - build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - "Callrecorder38@gmail.com"
        notify:
          success: true
          failure: true
