workflows:
  cordova_build:
    name: Cordova Build
    environment:
      java: 11
      android: true

    scripts:
      - name: Install dependencies
        script: |
          npm install -g cordova
          cordova platform add android

      - name: Build APK
        script: |
          cordova build android --release -- --keystore=keystore.jks --storePassword=yourpassword --alias=youralias --password=yourkeypassword

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk  # Forza la posizione specifica dell'APK

    publishing:
      email:
        recipients:
          - "Callrecorder38@gmail.com"  # Inserisci la tua email qui
        notify:
          success: true
          failure: true
