workflows:
  cordova_build:
    name: Build Cordova Android APK
    environment:
      java: "11"                   # Imposta Java 11
      node: "18"                   # Imposta Node 18
      android: true                # Abilita l'ambiente Android
    scripts:
      - name: Installazione Cordova
        script: |
          npm install -g cordova

      - name: Aggiunta piattaforma Android
        script: |
          cordova platform add android

      - name: Compilazione APK
        script: |
          cordova build android --release

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - "Callrecorder38@gmail.com"
        notify:
          success: true
          failure: true
