workflows:
  cordova_build:
    name: Cordova Build
    environment:
      flutter: stable
      java: "11"

    scripts:
      - name: Build Cordova Android APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - "Callrecorder38@gmail.com"
