workflows:
  android-debug-build:
    name: Android Debug Build
    environment:
      vars:
        ANDROID_APP_PATH: "platforms/android/app" # Percorso principale dell'app Android
        OUTPUT_APK_PATH: "platforms/android/app/build/outputs/apk/debug/app-debug.apk"
      android:
        image: latest
      java:
        version: 17 # Specifica la versione di Java
    scripts:
      - name: Installare dipendenze Cordova
        script: |
          npm install -g cordova
          cordova platform add android
      - name: Costruire l'app Android
        script: |
          cd $ANDROID_APP_PATH
          ./gradlew assembleDebug
      - name: Copiare APK negli artifacts
        script: |
          mkdir -p $CM_ARTIFACTS_DIR
          cp $OUTPUT_APK_PATH $CM_ARTIFACTS_DIR/
    artifacts:
      - $CM_ARTIFACTS_DIR/app-debug.apk
    publishing:
      email:
        recipients:
          - "Callrecorder38@gmail.com" # Sostituisci con il tuo indirizzo email
