name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Add Android Platform
        run: cordova platform add android@10.1.2

      - name: Build Android APK
        run: cordova build android --release

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: platforms/android/app/build/outputs/apk/release/*.apk
