name: Build Cordova Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build dell'immagine Docker
      - name: Build Docker image
        run: docker build -t cordova-android-build .

      # Esecuzione della build Cordova
      - name: Build APK using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            cordova-android-build

      # Archiviazione dell'APK come artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: platforms/android/app/build/outputs/apk/release/*.apk
