name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Dependencies
        run: npm install

      - name: Add Android Platform
        run: cordova platform add android@^10.1.2

      - name: Build Android APK
        run: cordova build android --release

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: platforms/android/app/build/outputs/apk/release/*.apk
