name: Build Cordova App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        channel: '7.x'

    - name: Install dependencies
      run: |
        npm install -g cordova
        cordova platform add android@latest

    - name: Build APK
      run: |
        cordova build android --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: platforms/android/app/build/outputs/apk/release/*.apk
