name: Build Cordova Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Cordova Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cordova
        run: npm install -g cordova

      - name: Setup Android environment
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-34 build-tools;34.0.0'
          accept-android-sdk-licenses: 'true'

      - name: Install project dependencies
        run: npm install

      - name: Add Android platform
        run: cordova platform add android@latest

      - name: Build the APK
        run: cordova build android --release

      - name: Debug APK directory
        run: ls -R platforms/android/app/build/outputs

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: platforms/android/app/build/outputs/apk/release/*.apk
