 name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Add Android Platform
        run: cordova platform add android@10.1.2

      - name: Install Android Build Tools
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
          yes | sdkmanager "build-tools;34.0.0" "platforms;android-34"

      - name: Build Android APK
        run: cordova build android --release

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: platforms/android/app/build/outputs/apk/release/*.apk
