name: Build Cordova App

on:
  push:
    branches:
      - main # Cambia con il nome del tuo branch principale
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Installazione Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installazione Cordova
      - name: Install Cordova
        run: npm install -g cordova

      # Installazione Android SDK e build tools
      - name: Setup Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          build-tools: 34.0.0
          target: default
          ndk: false

      # Copia dei file dalla cartella www
      - name: Prepare Cordova Project
        run: |
          mkdir cordova-project
          cp -r www cordova-project/
          cd cordova-project
          cordova create . com.example.appgiri "Registro Giri"
          cordova platform add android@13.0.0

      # Costruzione del progetto
      - name: Build APK
        run: |
          cd cordova-project
          cordova build android --release

      # Salvataggio degli artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: cordova-apk
          path: cordova-project/platforms/android/app/build/outputs/**/*.apk
